### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by not-matthias** [htl-perg-2019-20-5ahif/travel-planner-api-not-matthias#1]
@rauchi12 and I implemented all the required features.

**Comment by rstropek** [comment]
Nearly. Please use `IHttpClientFactory` in ASP.NET Core apps to get an instance of `HttpClient` (see [this slide](http://htl-mobile-computing-5.azurewebsites.net/#/6/1) and [this video](https://youtu.be/hj0joKgs01c?t=2512)). Fix that and the two extra points will be yours.

**Comment by not-matthias** [comment]
Alright, I implemented it. Is it okay to just add the[ base address in the constructor ](https://github.com/htl-perg-2019-20-5ahif/travel-planner-api-not-matthias/blob/master/web/Controllers/TravelPlannerController.cs#L22) or should we create a new client whenever we need one and use the entire URI as request parameter?
